### ISSUE TITLE
AUCTeX-style multifile support

### ISSUE THREAD

**Issue by nemethf** [astoff/digestif#1]
Reading about the TeXShop-style magic comments, it occurred to me that digestif might like to support AUCTeX-style multifile definitions as well, since eglot is emacs based. 
See: https://www.gnu.org/software/auctex/manual/auctex/Multifile.html#Multifile
This is an example at the end of a .tex file (note the extension from the file name is omitted):
```
     %%% Local Variables:
     %%% TeX-master: "master"
     %%% End:
```

Thanks

**Comment by nemethf** [comment]
Accidentally, I've bumped into the subfiles package, which could be used as an editor agnostic method to locate the root file.  Here's an example:
```
\documentclass[main.tex]{subfiles}
```
Details: https://jonasdevlieghere.com/modular-latex-with-subfiles/
Thanks again.

**Comment by astoff** [comment]
Thanks for the ideas. Before supporting AUCTeX magic comments, I think there should be a way to read user settings. To add support to any given package, the first step is to write a data file in the style of the existing ones.

**Comment by astoff** [comment]
Not implementing this is a good way to keep the codebase free of the "master/slave" metaphor, so I'll close this.
