### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by mmrezaie** [astoff/digestif#14]
Would it be possible to document better how it should be configured as a complete example? I am using lsp and company and when I do what documentation does it still doesn't provide the completion.

**Comment by astoff** [comment]
Can you provide more information about what went wrong? If you managed to install the server, there shouldn't be any further configuration you need to do.

**Comment by mmrezaie** [comment]
I was in the middle of writing all my configs and then I realized I have forgotten to install digestif on the PATH. I did the test on the wrong machine. Everything is working now. Thanks and I am sorry for the question since the documentation is complete as far as I See.
