### ISSUE TITLE
Could not find data files

### ISSUE THREAD

**Issue by ACov96** [astoff/digestif#2]
Whenever I try to run the server, I get the following:

```bash
$ digestif
/usr/bin/lua5.3: ...rocks/lib/luarocks/rocks-5.3/digestif/scm-1/bin/digestif:19: Could not find data files at the following locations:
  ./digestif-data
  /home/alex/.local/share/digestif-data
stack traceback:
	[C]: in function 'error'
	...rocks/lib/luarocks/rocks-5.3/digestif/scm-1/bin/digestif:19: in main chunk
	[C]: in ?
```

I installed using luarocks using the instructions in the README.

**Comment by astoff** [comment]
Where did luarocks install the `digestif-data` folder? You can find this with `locate digestif-data`. Also, can you provide the output of the command `luarocks show digestif` and let me know which OS you are using?

For now, if you copy the `digestif-data` folder in this repo to `/home/alex/.local/share/`, then it should work.
