### ISSUE TITLE
lpeg.so undefined symbol: lua_tointeger

### ISSUE THREAD

**Issue by xiaodongcentury** [astoff/digestif#21]
Hi, astoff!
Thank you for developing the fantastic package!

I'm using Debian Bullseye/Sid, GNU Emacs 28.0.50, debian apt install Lua 5.3 (Ver: Lua 5.3.3) and LuaRocks (Ver: 2.4.2).

As your follows, luarocks install digestif. Then ELPA install lsp-mode and company-lsp, at last, put the syntax (require 'company-lsp)
(add-to-list 'company-lsp-filter-candidates '(digestif . nil)) in init file.

Once open a tex file, Emacs minibuffer display "Server digestif:78655 status:starting exited with status exit." I check the *digestif* buffer, it's a blank buffer with size is 0. The *digestif::stderr* buffer says "/usr/bin/lua5.3: /usr/share/lua/5.3/luarocks/loader.lua:147: error loading module 'lpeg' from file '/usr/local/lib/lua/5.3/lpeg.so':
	/usr/local/lib/lua/5.3/lpeg.so: undefined symbol: lua_tointeger"
I check the /usr/local/lib/lua/5.3, and there is a file lpeg.so. So i open the loader.lua file, the line 144 is a function, and the line 147 local results = { a_loader(module_name) }

At the end, i don't know how to fix this error: undefined symbol
Hope the information above useful to you.
Thanks again.

**Comment by astoff** [comment]
This seems like an issue with your Lua installation. I see that lpeg.so is installed at /usr/local, while lua is at /usr/bin. So maybe you installed manually an incompatible version?

**Comment by xiaodongcentury** [comment]
Yeah, the problem is the location. I reinstall the Lua and LuaRocks from their github, so the digestif works fine. THX!
