### ISSUE TITLE
Cool Project :D

### ISSUE THREAD

**Issue by elliott-wen** [astoff/digestif#25]
This project is awesome. 

Though less powerful than Texlab, Digestif is efficient and lightweight.

I used Digestif in my own project SwiftLaTeX (https://www.swiftlatex.com), which is an online WebAssembly-based LaTeX editor. I compiled a Lua interpreter and digestif scripts into WebAssembly. It provides intelligence sense to my monaco editor.

Just one question, would it be possible to pack all documentations into the tag data files, so it does not have to rely on the info command.

Cheers

**Comment by astoff** [comment]
That's a cool project of yours! I'm pleasantly surprised that my program works in a platform I didn't anticipate.

I actually wanted to ship _fewer_ files, but I could create a mechanism to read the Info content cached in our internal `.tags` format; you could then generate these `.tags` with a simple script. Even simpler perhaps, I could make the `info:` hyperlinks "resolve" to normal links to the original <https://latexref.xyz/> when the info command is not available. But I must also say that I don't think this manual is ideal for "hover" help. I was hoping that, if Digestif picks up momentum, someone would find or create something more focused.

How is Texlab more powerful than Digestif? It's not my intention that this is so :-)

I'll mention SwiftLaTeX on the README, by the way.

**Comment by elliott-wen** [comment]
Thanks.

Sorry I didn’t mean TexLab is better. To me, TexLab is too bulky and a debug build can take up more than 300 mb space. And it’s slow in my computer. TexLab can do extra few things like rendering formulas and forward search. Nonetheless, these functionalities are not very important.

I will mention Digestif in my project too. Really nice to see it work flawless in browsers.

Cheers

**Comment by astoff** [comment]
Since there were no further discussions, I'll close this.
