### ISSUE TITLE
Attempt to call a nil value (method `all_environments`) with args (canditates)

### ISSUE THREAD

**Issue by acorbe** [astoff/digestif#27]
I am currently using digestif on emacs via lsp-mode  (emacs 26.3, just reinstalled everything from scratch. [config](https://github.com/acorbe/my-emacs-configuration/blob/feae3315fa445b8fe8935e4d7ab3e4666fba1374/emacs.el#L697)).

I am running lua 5.3.1 (via luaver) / digestif 0.3.1.

As I try to have auto-completion for the content of a `\begin{` block , I get the following error

```
Company: An error occurred in auto-begin
Company: backend company-capf error "...luarocks/2.3.0_5.3/share/lua/5.3/digestif/Manuscript.lua:867: attempt to call a nil value (method ’all_environments’)" with args (candidates it)
Auto-saving...done
```
![image](https://user-images.githubusercontent.com/2300692/88782289-b1b14480-d18d-11ea-8cc0-add10600e972.png)

any suggestion?

Thanks

**Comment by astoff** [comment]
This is fixed in the current git version

@acorbe You can run digestif via the [self-install script method](https://github.com/astoff/digestif#installation-and-set-up) to the get latest version.

**Comment by acorbe** [comment]
Thanks, awesome
