### ISSUE TITLE
VScode/Onivim2 support

### ISSUE THREAD

**Issue by gour** [astoff/digestif#28]
Hello,

I'd like to use Digestif for writing ConTeXt  markup, but wonder if it would be possible to use it with [Onivim 2](https://www.onivim.io/) editor which can use VScode extension or I need Vim+Coc?

**Comment by astoff** [comment]
Hi, it would be nice to have plugins for more editors. I'm not a VS Code user so I can't help with that, but it should be comparatively easy to do and I would be happy to advertise it here if someone creates an extension.

**Comment by gour** [comment]
@astoff Ok, in the meantime I'll try to see how it does work with Emacs. Which Emacs' lsp package would you recommend?
