### ISSUE TITLE
extra character "\" added before "{" when using environment snippet in neovim with coc.nvim

### ISSUE THREAD

**Issue by alexfanqi** [astoff/digestif#3]
I installed digestif as root on ubuntu 18.04 and use it with neovim v0.4.0-dev and coc.nvim  0.0.66.
Everything works pretty well except the extra "//" that I have to move cursor back and manually delete it. For example, when I type \begin and get completion prompt "begin~   {environment} [LS]" and I hit enter to choose it. Then I get "\begin\\{enviroment}". An extra "\\" is added before "{".

My coc.nvim config is like
"digestif": {                                               
                        command :  digestif ,                              
                        args : [],                                                  
                           filetypes : [                                      
                                  tex ,                                      
                                  plaintex ,                                 
                                  bibtex                                     
                          ],                                                  
                  }

**Comment by astoff** [comment]
Great to know it (mostly) works on neovim/coc!

I made the necessary change directly in the master branch. Does it work for you now?

**Comment by alexfanqi** [comment]
yes, it works perfectly now. Thanks for the great job and this great project!
