### ISSUE TITLE
Configure find definitions e references using \autoref instead of \ref

### ISSUE THREAD

**Issue by gutofarias** [astoff/digestif#32]
I've been using digestif and I'm very happy with it. Thanks for that nice piece of software.

I often use hyperref \autoref instead of \ref but I noticed that using hyperref I could not find references nor definitions.

Is there a way to configure the command \autoref to have the same lsp features of \ref?

I'm using eglot on emacs.

**Comment by astoff** [comment]
Unfortunately there's no automatic way to do this. You would have to create a tags file for hyperref.sty, similar to e.g. [latex.tags](https://github.com/astoff/digestif/blob/master/data/latex.tags).

The command `digestif --generate hyperref.sty.tags` will create a stub where you can fill in the details about the commands you care about.

**Comment by gutofarias** [comment]
Ok! Thank you

**Comment by astoff** [comment]
Since there were no further comments, I'll close this.
