### ISSUE TITLE
Path completion support?

### ISSUE THREAD

**Issue by nujabse** [astoff/digestif#35]
It would be nice if digestif can offer path completion function support. For example, when inserting images with `\includegraphics` command, it can show completion candidates based on file path when you are typing.

**Comment by astoff** [comment]
This is definitely a good feature to include. It should also cover commands that load files from the TeX installation as opposed to user files, such as `\documentclass`, `\usepackage`, etc.

**Comment by astoff** [comment]
I've added this now, but not for files inside subdirectories, which would be trickier to get right. Let me know if you find any issues.
