### ISSUE TITLE
invalid value (boolean) at index 1 in table for 'concat'

### ISSUE THREAD

**Issue by ZenWayne** [astoff/digestif#4]
```
stack traceback:
        [C]: in function 'table.concat'
        /usr/share/lua/5.3/luarocks/core/dir.lua:21: in function 'luarocks.core.dir.path'
        /usr/share/lua/5.3/luarocks/cmd.lua:160: in upvalue 'get_lua_version'
        /usr/share/lua/5.3/luarocks/cmd.lua:287: in function 'luarocks.cmd.run_command'
        /usr/bin/luarocks:38: in main chunk
        [C]: in ?
```
I execute the command 
`sudo luarocks install https://github.com/astoff/digestif/raw/master/rockspec/digestif-scm-1.rockspec`
get those errors

**Comment by astoff** [comment]
It seems your luarocks is not working. Maybe you should try to reinstall it. I've seen issues where different versions of lua are installed at the same time and create conflicts.

**Comment by ZenWayne** [comment]
thanks for the quick reply. It seems that it is because of luarocks.
I follow the issue [#1004](https://github.com/luarocks/luarocks/issues/1004#issue-438946104) from issue of luarocks and solve it finally.
