### ISSUE TITLE
Can I generate tag file from .bib file

### ISSUE THREAD

**Issue by deshearth** [astoff/digestif#40]
I use `digestif` with `eglot` in emacs. But when I put cursor under some citation key, it says "cite info is not available". I have to open the .bib file so that `digestif` can scan it. Also, the completion is not working either. Is there a way to let `digestif` know about my bibliography file? When I try to run `digestif -g /path/to/file.bib`, it says "can't generate tags from it".

**Comment by deshearth** [comment]
So if I use relative path to current tex file in bibliography command, the completions works perfectly. I used to put bib file name in that command because the path is under standard `TEXMFHOME`.

**Comment by astoff** [comment]
`"cite info is not available"` is a message from RefTeX, it has nothing to do with Digestif or Eglot. You can disable `reftex-mode` to get rid of it.

As you already noticed, Digestif reads bib files on the fly, no need to generate tags. 

Did you figure out the path thing, or do you still think there's a problem with Digestif causing it not to find your bib file?

**Comment by deshearth** [comment]
I see. So far I’ve been using relative path and it works well. I haven’t figured out the path thing but I guess it’s not a digestif issue.
