### ISSUE TITLE
Error during “textDocument/hover”: attempt to index a nil value (field 'data')

### ISSUE THREAD

**Issue by flying-sheep** [astoff/digestif#43]
```
[Error - 18:28:10] Request textDocument/hover failed.
  Message: /usr/share/lua/5.4/digestif/Manuscript.lua:552: attempt to index a nil value (field 'data')
  Code: 1 
```

referring to this line: https://github.com/astoff/digestif/blob/1fac471a153b99da7f858e63edfa19ec2afee791/digestif/Manuscript.lua#L552

**Comment by astoff** [comment]
Okay, the error is easy to fix. But do you have an example to reproduce this situation, so I can check the logic is right?

**Comment by flying-sheep** [comment]
Thank you! Sorry for not coming up with a reproducer!
