### ISSUE TITLE
ConTeXt environment-style section defintions don’t result in TOC entries

### ISSUE THREAD

**Issue by flying-sheep** [astoff/digestif#44]
Example document:

```context
\section{a}
\startsection[title={b}]
\stopsection
```

This should result in a TOC entry for both `a` and `b` with the same `section_level` but I only see `a`

**Comment by astoff** [comment]
I've pushed a fix. It has the side-effect that all start/stop commands are now treated as ordinary commands, e.g. they are available for completion. This seems all right to me but may have undesirable consequences. Let me know if you find any.

**Comment by flying-sheep** [comment]
Awesome! This indeed fixes it.

I think autocompleting \start* commands is a very nice thing, what kind of consequences do you expect?

**Comment by astoff** [comment]
Nothing in particular, I just mentioned it because I don't use ConTeXt very often.
