### ISSUE TITLE
How to generate tags file for completion?

### ISSUE THREAD

**Issue by lavish440** [astoff/digestif#45]
I am currently using digestif with coc.nvim. I installed digestif using luarocks but I didn't get any autocompletion. Whenever I try to generate tags file, digestif gives me an error 
 

`
digestif --generate $(kpsewhich amsmath.sty)`

```bash 
Error: can't find '/usr/share/texmf-dist/tex/latex/amsmath/amsmath.sty' or can't generate tags from it. 
```

**Comment by astoff** [comment]
This command works for me using the git master branch. Could you try that?

But before delving into the autogenerated stuff, do you get completions for the basic LaTeX commands, say, `\cite` or `\section`?

**Comment by lavish440** [comment]
No. I don't get any autocompletion at all.

**Comment by lavish440** [comment]
@astoff Respond please What should I do?

**Comment by astoff** [comment]
If you get no completions at all, then there must be some problem in your text editor configuration.

**Comment by lavish440** [comment]
There is no problem with my Neovim configuration as texlab, clangd and ccls work fine. Also I have seen from logs that digestif is successfully connected to coc.

**Comment by lavish440** [comment]
[coc.log](https://github.com/astoff/digestif/files/9470963/coc.log)
This is the output of `:CocCommand workspace.showOutput languageserver.digestif`

**Comment by lavish440** [comment]
[coc.log](https://github.com/astoff/digestif/files/9470963/coc.log)
This is the output of `:CocCommand workspace.showOutput languageserver.digestif`

**Comment by lavish440** [comment]
```json
{
    "languageserver": {
      "digestif": {
        "command": "/home/lavish/.luarocks/bin/digestif",
        "filetypes": ["tex", "plaintex", "context"],
        "trace.server": "verbose"
      }
    },
    "Lua.telemetry.enable": false
}
```
@astoff This is my coc config

**Comment by astoff** [comment]
I see nothing obviously wrong with your configuration, so I'm afraid I can't help more. You might have better luck with a newer version installed with the [self-installing wrapper script](https://github.com/astoff/digestif#luatex-with-the-self-installing-script-).

**Comment by lavish440** [comment]
Then What if I need autocompletion for .sty files like amsmath?

**Comment by lavish440** [comment]
@astoff I have installed digestif using the wrapper script. I have generated .tags file for amsmath.sty and copied it to ~/.digestif/data successfully but still I am not getting any completion for anything.

**Comment by astoff** [comment]
I'll close this now, but if in the future you want to discuss the inclusion of a tags file, please feel free to open a new ticket.
