### ISSUE TITLE
Fuzzy completion definitely works with `corfu`!

### ISSUE THREAD

**Issue by hammerfunctor** [astoff/digestif#47]
> The fuzzy completion features is known to work in conjunction with [Company mode](https://company-mode.github.io/). Other completion UIs may be incompatible.

`Corfu`+`eglot` with any configuration:
![Screenshot_20220829_013053](https://user-images.githubusercontent.com/65394269/187129508-f0c7592a-1794-4f45-89c7-c7eb23affd45.png)

**Comment by manuel-uberti** [comment]
@astoff Would it make sense to mention `corfu` in the README (maybe point at this ticket for reference) and close this ticket?

**Comment by astoff** [comment]
Can you confirm that you get the same behavior? Last time I tried, I wasn't able. Also, I suspect this screenshot is using the (rather old) version 0.4 from luarocks, not the current Git version.

**Comment by manuel-uberti** [comment]
> Can you confirm that you get the same behavior? Last time I tried, I wasn't able. Also, I suspect this screenshot is using the (rather old) version 0.4 from luarocks, not the current Git version.

It works with latest `digestif` and `completion-styles` set to `flex`. FTR, it works just as well with `orderless`.

**Comment by hammerfunctor** [comment]
I haven't set up anything for it. It works out of the box with digestif installed from AUR `digestif-git` (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=digestif-git), a latest git installation. Though it does fail to prompt completion when it found multiple bib files with the same name, one of which is located in like `/usr/local/share/texmf/bibtex/bib/`, I don't think this behavior results from the completion front end.
