### ISSUE TITLE
Unable to report version

### ISSUE THREAD

**Issue by raxod502** [astoff/digestif#50]
When attempting to retrieve the currently installed version of Digestif, I receive an error message:

```
% digestif --version
Usage: digestif [-h] [-v] [-g FILES]

Invalid option: --version
```

I think it would be an improvement if the current version number were printed instead.

**Comment by astoff** [comment]
Yes, makes sense. I just need to think how to handle the case where it's installed through the [self-installing script](https://github.com/astoff/digestif#luatex-with-the-self-installing-script-).

**Comment by nemethf** [comment]
Can you, please, return this information in the [InitializeResult](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeResult) reply as well? Thank you.

**Comment by raxod502** [comment]
Amazing! Thank you!
