### ISSUE TITLE
Can I use this lsp on Windows? If that, could you give me some suggestions?

### ISSUE THREAD

**Issue by yanpeng** [astoff/digestif#51]
I download this repo using that `digestif.cmd`, and set the `bin` folder path into the `PATH` environment variable. After open a `.tex` document in Emacs, `M-x eglot`, it failed to find this `digestif`. I think the problem is that, the `digestif` program inside the `bin` folder is not really a real Windows executable.

So, facing this problem, how can I install `digestif` successfully on Windows? Thanks in advance.

**Comment by astoff** [comment]
You can try `C-u M-x eglot RET`, which will make Eglot ask for the server name. Then type the absolute file name of `digestif.cmd`.

If that works, then you can try again to find a place to put `digestif.cmd` so Windows will find it (typing `echo %PATH%` in the command prompt should give you some hints), or you can just modify `eglot-server-programs` and replace the `digestif` command with the absolute name of the script.

I hope this helps!
