### ISSUE TITLE
Adding a .dir-locals.el to the repo

### ISSUE THREAD

**Issue by dr-scsi** [astoff/digestif#57]
Hi,

would you consider adding a `.dir-locals.el` to the repo?  This could help people who want to contribute and use Emacs for coding.  A skeleton can look like this:

```lisp
;;; Directory Local Variables            -*- no-byte-compile: t -*-
;;; For more information see (info "(emacs) Directory Variables")

((nil . ((indent-tabs-mode . nil)))
 (auto-mode-alist . (("\\.tags\\'" . lua-mode)
                     ("\\.texlua\\'" . lua-mode)
                     ("\\.rockspec\\'" . lua-mode)))
 (lua-mode . ((lua-indent-level . 2))))

```

**Comment by astoff** [comment]
I've added a version of this [to the wiki](https://github.com/astoff/digestif/wiki/Editor-configuration). Thanks!
