### ISSUE TITLE
publish on luarocks.org ?

### ISSUE THREAD

**Issue by teto** [astoff/digestif#6]
I have some tooling that generates packages from luarocks that are on www.luarocks.org (I should adapt it to fetch the rockspec from any source really) so I wonder if you could post your rockspec on luarocks.org please ?
Would also make it easier to install.
I could do it but I don't want to hijack the name in the global namespace ;)

**Comment by astoff** [comment]
OK, I did it! Let me know if it works.

**Comment by teto** [comment]
any reason you didn't want to push to the main manifest ?
It means luarocks install digestif won't work, people will have to use `luarocks install --server=http://luarocks.org/dev digestif`. It's not a problem for my usecase but I wondered why.
 
I hadn't seen it required lua 5.3 `digestif supports only Lua 5.3 and Lua 5.4 but not Lua 5.2.` but from there I can manage by myself thanks !
