### ISSUE TITLE
Multifile projects support

### ISSUE THREAD

**Issue by innerout** [astoff/digestif#7]
Hello astoff thanks for the great package you have developed.
I would like to ask you if multifile latex projects are supported? 
If not do you intend to add support for them later?

**Comment by astoff** [comment]
As explained in the README, you can use TeXShop-style magic comments. Try adding sometihng like `% !TeX root = somefile.tex` near the top of each child tex file.

**Comment by innerout** [comment]
I tried it but i don't get autocomplete features for the citations for example.

**Comment by astoff** [comment]
OK, I can look into this if you provide more information. Do you get autocomplete for labels (`\ref`)? Which bibliography system are you using? (Only old-style bibtex is implemented for now.)

If you can, please post a minimal example to reproduce the bug.

**Comment by innerout** [comment]
I am using the old-style bibtex. I get autocompletions from your lsp server for commands like \ref or \cite but i don't get autocompletions for their markers. 

A minimal setup to reproduce is to have a directory with an old-styled paper.bib, paper.tex and side.tex where side.tex would be used as \input side in paper.tex.

**Comment by astoff** [comment]
Is this plain TeX or LaTeX? For plain, cross-references are not implemented yet. For LaTeX, you should use `\include` instead of `\input` for now (I'll fix this).

**Comment by innerout** [comment]
I forgot to mention this is LaTeX. I will try ```\include``` and report back.
